[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "no-std",
]
keywords = [
    "arm",
    "cortex-m",
    "template",
    "nrf51",
    "hal",
]
name = "nrf51-hal"
version = "0.1.0"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.2"
embedded-hal = "0.1.0"
nb = "0.1.1"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.nrf51]
features = ["rt"]
git = "https://github.com/therealprof/nrf51"

[features]
default = ["rt"]
rt = []
[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
